# Generated by Django 2.2 on 2020-04-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200428_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
